# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: Richard Kuesers
author-title: Full Stack you-name-it
gravatar: 818c9411023d464a1a03c3c1af37b00f
email: rkuesters@gmail.com
twitter: vltr
github: vltr
googleplus: +RichardKuesters
facebook:
linkedin: rkuesters/en
bio: "i'm a computer programmer, analyst, software architect, tech enthusiast, ift admin and lots of things in between."

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values
front-end:
  - name: HTML 5
    level: 4
  - name: CSS 3
    level: 4
  - name: JavaScript
    level: 5
  - name: Angular 1.x
    level: 4
  - name: Bootstrap
    level: 4
  - name: LESS
    level: 4
  - name: SASS / libsass
    level: 4
  - name: Jade
    level: 4
  - name: Grunt
    level: 4
  - name: Bower
    level: 4

back-end:
  - name: Node.js
    level: 5
  - name: Python
    level: 5
  - name: Java
    level: 4
  - name: C and CPP
    level: 4
  - name: SQL
    level: 4
  - name: C#
    level: 3
  - name: Bash
    level: 3
  - name: T-SQL
    level: 3
  - name: pgPL/SQL
    level: 4
  - name: PL/SQL
    level: 4

mobile:
  # - name: Android
  #   level: 2
  # - name: Apache Cordova
  #   level: 4
  # - name: Ionic
  #   level: 4
  # - name: NativeScript
  #   level: 3

db:
  - name: MySQL / MariaDB
    level: 4
  - name: PostgreSQL
    level: 5
  - name: MongoDB
    level: 3
  - name: SQL Server
    level: 4
  - name: Oracle
    level: 4
  - name: Redis
    level: 4
  - name: SQLite
    level: 5

devops:
  - name: Jenkins
    level: 3
  - name: Git
    level: 5
  - name: Apache Maven
    level: 4
  - name: Continuous Integration
    level: 4
  - name: Continuous Delivery
    level: 4
  - name: System Administration
    level: 5
  - name: Troubleshooting
    level: 5

methodologies:
  - name: ToC - Theory of Constraints
    level: 5

others:
  - name: Qt
    level: 4
  - name: SQLAlchemy
    level: 5
  - name: Twisted Matrix
    level: 4
  - name: Linux
    level: 5
  - name: Cryptography
    level: 3
  - name: ActiveMQ
    level: 4

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap, bourbon]
