# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: Richard Kuesters
author-title: IT Specialist (aka. full stack [you-name-it] || troubleshooter)
gravatar: 818c9411023d464a1a03c3c1af37b00f
email: rkuesters@gmail.com
twitter: vltr
github: vltr
googleplus: +RichardKuesters
facebook:
linkedin: rkuesters/en
bio: "Being an IT specialist and product development leader of industry level softwares, it is of my greatest interest in this continuous growth of my capabilities, not only as a leader - when such required - but also as a person, professional and passionate developer, using everything that I have learned so I can give employers the same level of growth and enthusiam I can develop on a daily basis on everything I'm engaged to."

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values
front-end:
  - name: HTML 5
    level: 5
  - name: CSS 3
    level: 5
  - name: JavaScript
    level: 5
  - name: Angular 1.x
    level: 4
  - name: jQuery
    level: 4
  - name: Bootstrap
    level: 4
  - name: LESS
    level: 4
  - name: SASS / libsass
    level: 4
  - name: Jade
    level: 4
  - name: Grunt
    level: 4
  - name: Gulp
    level: 3

back-end:
  - name: Node.js
    level: 5
  - name: Python
    level: 5
  - name: C and CPP
    level: 4
  - name: SQL
    level: 5
  - name: C#
    level: 3
  - name: Bash
    level: 4
  - name: T-SQL
    level: 3
  - name: pgPL/SQL
    level: 4
  - name: PL/SQL
    level: 4
  - name: Java
    level: 5
  - name: Flask (Python)
    level: 4

mobile:
  - name: Android (Java)
    level: 3
  - name: iOS (Swift)
    level: 3
  - name: Any (CPP cross-platform)
    level: 4

db:
  - name: MySQL / MariaDB
    level: 4
  - name: PostgreSQL
    level: 5
  - name: MongoDB
    level: 3
  - name: SQL Server
    level: 4
  - name: Oracle
    level: 4
  - name: Redis
    level: 4
  - name: SQLite
    level: 5

devops:
  - name: Jenkins
    level: 3
  - name: Git
    level: 5
  - name: Apache Maven
    level: 4
  - name: Continuous Integration
    level: 4
  - name: Continuous Delivery
    level: 4
  - name: System Administration
    level: 5
  - name: Troubleshooting
    level: 5
  - name: AWS
    level: 4

methodologies:
  - name: ToC - Theory of Constraints
    level: 5

others:
  - name: Qt
    level: 4
  - name: SQLAlchemy
    level: 5
  - name: Twisted Matrix
    level: 4
  - name: Linux
    level: 5
  - name: Cryptography
    level: 3
  - name: ActiveMQ
    level: 4
  - name: Java
    level: 4
  - name: Cloud-stuff (VMs, IaaS, PaaS, Sandboxes, Containers, etc)
    level: 5

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap, bourbon]
